### ISSUE TITLE
Crash In -[BOZPongRefreshControl setGamePiecePositionsForAnimationStop:]

### ISSUE THREAD

**Issue by iAdam1n** [hbang/Pheromone#20] opened 2015-07-30 12:32 UTC
Crash: https://ghostbin.com/paste/7xo2v

Syslog: https://ghostbin.com/paste/qq2bq

**Comment by nintyapple** [comment] 2015-07-30 22:35
pir8
![PIRACY IS BAD PLS NO PIRACY](https://cloud.githubusercontent.com/assets/5097035/8996888/a63cf44e-36e9-11e5-8db4-d3b721dcf308.jpg)

**Comment by kirb** [comment] 2017-06-19 05:19
Closing as dupe of #18.

**Closed as completed by kirb** 2017-06-19 05:19 UTC
Labels: bug
