### ISSUE TITLE
Overlay bug in cydia after adding repo

### ISSUE THREAD

**Issue by afrorowan** [hbang/Pheromone#9] opened 2015-07-07 17:45 UTC
![img_1963](https://cloud.githubusercontent.com/assets/13224142/8552962/6d97f78a-24e0-11e5-98a0-3dc7d316777f.PNG)

Cydia tweaks installed:
- SwipeForMore 1.0-2
- Pheromone 1.0~beta2

iPhone6,2, iOS 8.4, Cydia 1.1.20

**Comment by iAdam1n** [comment] 2015-07-07 17:55
Duplicate of https://github.com/hbang/Pheromone/issues/6

**Closed as completed by iAdam1n** 2015-07-07 17:55 UTC
