### ISSUE TITLE
Individual sources

### ISSUE THREAD

**Issue by jayreddin** [hbang/Pheromone#7] opened 2015-07-07 02:25 UTC
the individual sources banner under sources stays staic and stays in the top middle of the screen

**Comment by jayreddin** [comment] 2015-07-07 02:25
Static

**Comment by jayreddin** [comment] 2015-07-07 02:26
Only when refreshing sources

**Comment by ReddestDream** [comment] 2015-07-07 02:57
I noticed the same thing:

https://github.com/hbang/Pheromone/issues/6

**Comment by kirb** [comment] 2015-07-07 08:12
Do you mean the same as what @ReddestDream reported? If so I'll close this issue as a duplicate of that one.

**Comment by jayreddin** [comment] 2015-07-07 08:49
Yeah I presume it is the same. Its as sources are loading the individual sources banner stays static on screen and doesn't move move with the rest of the screen

**Comment by jayreddin** [comment] 2015-07-07 08:51
Found another. As sources are loading if you press edit the ping pong animations stay on screen until you press done. Even after sources stop loading.

**Comment by jayreddin** [comment] 2015-07-07 08:58
Also the ping pong animation freezes on screen if you keep pressing the "Refresh/X" in the top left corner

**Comment by ReddestDream** [comment] 2015-07-07 10:01
I've also reported freezing issues with the pong animation although I did not try editing sources.

https://github.com/hbang/Pheromone/issues/6

**Closed as completed** 2015-07-07 17:53 UTC
